diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=juanmeraagudelo@gmail.com
user.name=JuanPabloA1
safe.directory=D:/UltimoBackUp/Documentos/Tecni-Electronica/backend-application
safe.directory=D:/UltimoBackUp/Documentos/admi
safe.directory=D:/UltimoBackUp/Documentos/admi
safe.directory=D:/UltimoBackUp/Documentos/admi
safe.directory=D:/UltimoBackUp/Documentos/admin-dashboard-angular/admin-dashboard
safe.directory=D:/UltimoBackUp/Documentos/platzi-angular
safe.directory=D:/UltimoBackUp/Documentos/pruebas-unitarias-spring-boot
safe.directory=D:/Desktop/OlSoftware/lab_api_spring_boot
core.autocrlf=true
difftool.sourcetree.cmd='' 
mergetool.sourcetree.cmd='' 
mergetool.sourcetree.trustexitcode=true
